disabled_rules:
  - identifier_name
  - inclusive_language
  - shorthand_operator

excluded:
  - Pods

line_length:
  - 160 # warning
  - 300 # error

type_body_length:
  - 350 # warning

type_name:
  allowed_symbols: ["_"] # for previews
